version: "3.8"
services:
  nginx:
    image: nginx
    ports:
    - "8000:80"
    depends_on:
    - php-fpm
    volumes:
    - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www/html
  php-fpm:
    build:
      context: .
      dockerfile: ./_docker/php-fpm/Dockerfile
    depends_on:
    - mysql
    volumes:
    - .:/var/www/html
  mysql:
    build:
      context: .
      dockerfile: ./_docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
    - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
volumes:
  mysql-data: